package semanticplan

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"reflect"
	"slices"
	"sort"
	"strings"

	"github.com/aminkbi/d-raft/artifact"
	"github.com/aminkbi/d-raft/decision"
	"github.com/aminkbi/d-raft/internal/strictjson"
)

// CausalReplaySchema identifies operation-level replay evidence. It is
// separate from occurrence projection because occurrence coverage can move a
// loss to a different logical operation after a message reorder.
const (
	CausalReplaySchema   = "d-raft.causal-replay/v1"
	CausalEvidenceSchema = "d-raft.causal-evidence/v1"
)

var (
	ErrInvalidCausal  = errors.New("semanticplan: invalid causal replay")
	ErrCausalConflict = errors.New("semanticplan: conflicting causal batch")
)

// CausalDirective gives every attempt of one operation the same disposition.
// SourceIndices retain the source-tape provenance for audit and reduction.
type CausalDirective struct {
	OperationID   string             `json:"operation_id"`
	SourceIndices []artifact.Uint64  `json:"source_indices"`
	Selection     decision.Selection `json:"selection"`
}

type CausalProjectionReport struct {
	Schema     string             `json:"schema"`
	Fidelity   ProjectionFidelity `json:"fidelity"`
	Directives int                `json:"directives"`
	Projected  int                `json:"projected"`
	Additional []string           `json:"additional"`
	Unmatched  []CausalDirective  `json:"unmatched"`
}

// CausalReplayEvidence is the bounded, durable source/target envelope for a
// successful causal projection. It keeps source and target outcomes separate:
// equal outcomes are not required for an independent adapter, while both
// tapes and the causal accounting remain independently checkable.
type CausalReplayEvidence struct {
	Schema        string                 `json:"schema"`
	PlanSHA256    string                 `json:"plan_sha256"`
	SourceAdapter artifact.Adapter       `json:"source_adapter"`
	TargetAdapter artifact.Adapter       `json:"target_adapter"`
	FallbackSeed  artifact.Uint64        `json:"fallback_seed"`
	SourceTape    decision.Tape          `json:"source_tape"`
	TargetTape    decision.Tape          `json:"target_tape"`
	SourceOutcome artifact.Outcome       `json:"source_outcome"`
	TargetOutcome artifact.Outcome       `json:"target_outcome"`
	Report        CausalProjectionReport `json:"report"`
}

// Validate verifies causal markers, exact target-local selections, and the
// report generated by those selections. A failed projection is intentionally
// not represented as replayable evidence because its rejected choice is not in
// the target tape.
func (e CausalReplayEvidence) Validate() error {
	if e.Schema != CausalEvidenceSchema {
		return fmt.Errorf("%w: unsupported evidence schema %q", ErrInvalidCausal, e.Schema)
	}
	if !digestPattern.MatchString(e.PlanSHA256) {
		return fmt.Errorf("%w: plan hash must be lowercase SHA-256", ErrInvalidCausal)
	}
	if err := validateAdapterID(e.SourceAdapter); err != nil {
		return fmt.Errorf("%w: source adapter: %v", ErrInvalidCausal, err)
	}
	if err := validateAdapterID(e.TargetAdapter); err != nil {
		return fmt.Errorf("%w: target adapter: %v", ErrInvalidCausal, err)
	}
	if err := ValidateCausalTape(e.SourceTape); err != nil {
		return err
	}
	if err := ValidateCausalTape(e.TargetTape); err != nil {
		return fmt.Errorf("%w: target tape: %v", ErrInvalidCausal, err)
	}
	if _, err := decision.NewCausalTapeDecider(e.TargetTape); err != nil {
		return fmt.Errorf("%w: target tape: %v", ErrInvalidCausal, err)
	}
	if err := e.Report.Validate(); err != nil {
		return err
	}
	if e.Report.Fidelity == ProjectionFailed {
		return fmt.Errorf("%w: failed projections require a separate rejected-choice record", ErrInvalidCausal)
	}
	if err := validateRawOutcome(e.SourceOutcome); err != nil {
		return fmt.Errorf("%w: source outcome: %v", ErrInvalidCausal, err)
	}
	if err := validateRawOutcome(e.TargetOutcome); err != nil {
		return fmt.Errorf("%w: target outcome: %v", ErrInvalidCausal, err)
	}
	directives, err := CausalDirectivesFromTape(e.SourceTape)
	if err != nil {
		return err
	}
	projector, err := NewCausalProjector(directives, e.FallbackSeed)
	if err != nil {
		return err
	}
	for index, entry := range e.TargetTape.Entries {
		selection, chooseErr := projector.Choose(entry.Choice)
		if chooseErr != nil {
			return fmt.Errorf("%w: target choice %d: %v", ErrInvalidCausal, index, chooseErr)
		}
		if !reflect.DeepEqual(selection, entry.Selection) {
			return fmt.Errorf("%w: target choice %d selection differs from causal projection", ErrInvalidCausal, index)
		}
	}
	if !reflect.DeepEqual(projector.Finish(), e.Report) {
		return fmt.Errorf("%w: report does not match target tape", ErrInvalidCausal)
	}
	encoded, err := json.Marshal(e)
	if err != nil || len(encoded) > artifact.DefaultMaxArtifactBytes {
		return fmt.Errorf("%w: evidence exceeds resource budget", ErrInvalidCausal)
	}
	return nil
}

// DecodeCausalReplayEvidence strictly decodes one bounded causal evidence
// document.
func DecodeCausalReplayEvidence(reader io.Reader) (CausalReplayEvidence, error) {
	var evidence CausalReplayEvidence
	if err := decodePlanDocument(reader, artifact.DefaultMaxArtifactBytes, &evidence); err != nil {
		return CausalReplayEvidence{}, fmt.Errorf("%w: %v", ErrInvalidCausal, err)
	}
	if err := evidence.Validate(); err != nil {
		return CausalReplayEvidence{}, err
	}
	return evidence, nil
}

// DigestCausalReplayEvidence returns the SHA-256 of a validated canonical
// evidence document.
func DigestCausalReplayEvidence(evidence CausalReplayEvidence) (string, error) {
	if err := evidence.Validate(); err != nil {
		return "", err
	}
	return digestCanonicalJSON(evidence)
}

// Validate rejects malformed or non-canonical causal accounting. Reports are
// standalone evidence documents, so validation does not require the source
// tape or target execution to be present.
func (report CausalProjectionReport) Validate() error {
	if report.Schema != CausalReplaySchema {
		return fmt.Errorf("%w: unsupported report schema %q", ErrInvalidCausal, report.Schema)
	}
	if report.Fidelity != ProjectionExact && report.Fidelity != ProjectionPartial && report.Fidelity != ProjectionFailed {
		return fmt.Errorf("%w: invalid report fidelity %q", ErrInvalidCausal, report.Fidelity)
	}
	if report.Directives < 0 || report.Directives > artifact.MaxDecisions || report.Projected < 0 || report.Projected > report.Directives {
		return fmt.Errorf("%w: invalid report counts", ErrInvalidCausal)
	}
	if report.Additional == nil || report.Unmatched == nil {
		return fmt.Errorf("%w: report lists must be non-null", ErrInvalidCausal)
	}
	for index, id := range report.Additional {
		if id == "" || len(id) > 128 || strings.TrimSpace(id) != id || index > 0 && report.Additional[index-1] >= id {
			return fmt.Errorf("%w: additional IDs must be sorted, unique, and bounded", ErrInvalidCausal)
		}
	}
	if err := ValidateCausalDirectives(report.Unmatched); err != nil {
		return err
	}
	if len(report.Unmatched) > report.Directives {
		return fmt.Errorf("%w: unmatched directives exceed directive count", ErrInvalidCausal)
	}
	if report.Fidelity == ProjectionExact && (len(report.Additional) != 0 || len(report.Unmatched) != 0 || report.Projected != report.Directives) {
		return fmt.Errorf("%w: exact report has uncovered choices", ErrInvalidCausal)
	}
	if report.Fidelity == ProjectionPartial && len(report.Additional) == 0 && len(report.Unmatched) == 0 && report.Projected == report.Directives {
		return fmt.Errorf("%w: partial report has no uncovered choices", ErrInvalidCausal)
	}
	encoded, err := json.Marshal(report)
	if err != nil || len(encoded) > artifact.DefaultMaxArtifactBytes {
		return fmt.Errorf("%w: report exceeds resource budget", ErrInvalidCausal)
	}
	return nil
}

// DecodeCausalProjectionReport strictly decodes one bounded causal report.
func DecodeCausalProjectionReport(reader io.Reader) (CausalProjectionReport, error) {
	var report CausalProjectionReport
	if err := decodePlanDocument(reader, artifact.DefaultMaxArtifactBytes, &report); err != nil {
		return CausalProjectionReport{}, fmt.Errorf("%w: %v", ErrInvalidCausal, err)
	}
	if err := report.Validate(); err != nil {
		return CausalProjectionReport{}, err
	}
	return report, nil
}

func CausalDirectivesFromTape(tape decision.Tape) ([]CausalDirective, error) {
	if err := ValidateCausalTape(tape); err != nil {
		return nil, err
	}
	byID := make(map[string]CausalDirective)
	for index, entry := range tape.Entries {
		if entry.Choice.Kind != decision.NetworkLoss {
			continue
		}
		ids, causal, err := choiceOperationContext(entry.Choice)
		if err != nil {
			return nil, fmt.Errorf("%w: choice %d: %v", ErrInvalidCausal, index, err)
		}
		if !causal {
			return nil, fmt.Errorf("%w: source choice %d is missing the causal context marker", ErrInvalidCausal, index)
		}
		for _, id := range ids {
			if entry.Selection.Option != "drop" && entry.Selection.Option != "deliver" {
				return nil, fmt.Errorf("%w: choice %d is not a loss selection", ErrInvalidCausal, index)
			}
			d := byID[id]
			if d.OperationID == "" {
				d = CausalDirective{OperationID: id, SourceIndices: []artifact.Uint64{}, Selection: cloneSelection(entry.Selection)}
			} else if !reflect.DeepEqual(d.Selection, entry.Selection) {
				return nil, fmt.Errorf("%w: operation %s has conflicting dispositions", ErrCausalConflict, id)
			}
			d.SourceIndices = append(d.SourceIndices, artifact.Uint64(index))
			byID[id] = d
		}
	}
	result := make([]CausalDirective, 0, len(byID))
	for _, d := range byID {
		result = append(result, d)
	}
	sort.Slice(result, func(i, j int) bool { return result[i].OperationID < result[j].OperationID })
	return result, ValidateCausalDirectives(result)
}

// ValidateCausalTape ensures a source tape was produced by an opt-in causal
// run. Ordinary v1 tapes are deliberately rejected instead of being silently
// interpreted as having no operation-level directives.
func ValidateCausalTape(tape decision.Tape) error {
	if _, err := decision.NewCausalTapeDecider(tape); err != nil {
		return fmt.Errorf("%w: source tape: %v", ErrInvalidCausal, err)
	}
	sawLoss := false
	for index, entry := range tape.Entries {
		if entry.Choice.Kind != decision.NetworkLoss {
			continue
		}
		sawLoss = true
		_, causal, err := choiceOperationContext(entry.Choice)
		if err != nil {
			return fmt.Errorf("%w: source choice %d: %v", ErrInvalidCausal, index, err)
		}
		if !causal {
			return fmt.Errorf("%w: source choice %d is not causal", ErrInvalidCausal, index)
		}
	}
	if !sawLoss {
		return fmt.Errorf("%w: source tape has no causal network-loss contexts", ErrInvalidCausal)
	}
	return nil
}

func ValidateCausalDirectives(directives []CausalDirective) error {
	previous := ""
	for index, d := range directives {
		if d.OperationID == "" || len(d.OperationID) > 128 || strings.TrimSpace(d.OperationID) != d.OperationID {
			return fmt.Errorf("%w: directives[%d] operation ID", ErrInvalidCausal, index)
		}
		if index > 0 && previous >= d.OperationID {
			return fmt.Errorf("%w: directives must be sorted and unique", ErrInvalidCausal)
		}
		previous = d.OperationID
		if len(d.SourceIndices) == 0 || d.SourceIndices == nil {
			return fmt.Errorf("%w: directives[%d] has no source provenance", ErrInvalidCausal, index)
		}
		for i, sourceIndex := range d.SourceIndices {
			if uint64(sourceIndex) >= artifact.MaxDecisions || i > 0 && d.SourceIndices[i-1] >= sourceIndex {
				return fmt.Errorf("%w: directives[%d] source indexes", ErrInvalidCausal, index)
			}
		}
		if d.Selection.Number != nil || d.Selection.Option != "drop" && d.Selection.Option != "deliver" {
			return fmt.Errorf("%w: directives[%d] selection", ErrInvalidCausal, index)
		}
	}
	return nil
}

// ChoiceOperationIDs reads the optional causal identity from a network-loss
// context. Adapter-local fields remain available for exact local replay.
func ChoiceOperationIDs(choice decision.Choice) ([]string, error) {
	ids, _, err := choiceOperationContext(choice)
	return ids, err
}

func choiceOperationContext(choice decision.Choice) ([]string, bool, error) {
	if choice.Kind != decision.NetworkLoss || len(choice.Context) == 0 {
		return []string{}, false, nil
	}
	if err := strictjson.RejectDuplicateNames(choice.Context); err != nil {
		return nil, false, err
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(choice.Context, &fields); err != nil {
		return nil, false, err
	}
	causal := false
	if raw, ok := fields["causal"]; ok {
		if err := json.Unmarshal(raw, &causal); err != nil {
			return nil, false, errors.New("causal must be a boolean")
		}
	}
	raw, ok := fields["operation_ids"]
	if !ok {
		return []string{}, causal, nil
	}
	var ids []string
	if err := json.Unmarshal(raw, &ids); err != nil || ids == nil {
		return nil, false, errors.New("operation_ids must be a non-null array")
	}
	for i, id := range ids {
		if id == "" || len(id) > 128 || strings.TrimSpace(id) != id || i > 0 && ids[i-1] >= id {
			return nil, false, errors.New("operation_ids must be sorted, unique, and bounded")
		}
	}
	return ids, causal, nil
}

// CausalProjector applies one source disposition to all attempts of an
// operation. A dropped known operation cannot share an indivisible target
// batch with an unmapped operation; that mapping is rejected before execution.
type CausalProjector struct {
	directives map[string]CausalDirective
	consumed   map[string]struct{}
	additional map[string]struct{}
	fallback   *decision.SeedDecider
	failed     error
}

func NewCausalProjector(directives []CausalDirective, fallbackSeed artifact.Uint64) (*CausalProjector, error) {
	if err := ValidateCausalDirectives(directives); err != nil {
		return nil, err
	}
	p := &CausalProjector{directives: map[string]CausalDirective{}, consumed: map[string]struct{}{}, additional: map[string]struct{}{}, fallback: decision.NewSeedDecider(uint64(fallbackSeed))}
	for _, d := range directives {
		p.directives[d.OperationID] = d
	}
	return p, nil
}

func (p *CausalProjector) IncludeOperationIDs() bool { return true }

func (p *CausalProjector) Choose(choice decision.Choice) (decision.Selection, error) {
	if p == nil || p.failed != nil {
		if p == nil {
			return decision.Selection{}, ErrInvalidCausal
		}
		return decision.Selection{}, p.failed
	}
	if err := decision.ValidateChoice(choice); err != nil {
		return decision.Selection{}, p.fail(err)
	}
	if choice.Kind != decision.NetworkLoss {
		selection, err := p.fallback.Choose(choice)
		if err != nil {
			return decision.Selection{}, p.fail(err)
		}
		p.additional[choice.ID] = struct{}{}
		return selection, nil
	}
	ids, causal, err := choiceOperationContext(choice)
	if err != nil {
		return decision.Selection{}, p.fail(fmt.Errorf("%w: %v", ErrInvalidCausal, err))
	}
	if !causal {
		return decision.Selection{}, p.fail(fmt.Errorf("%w: target choice lacks causal context marker", ErrInvalidCausal))
	}
	if len(ids) == 0 {
		selection, err := p.fallback.Choose(choice)
		if err != nil {
			return decision.Selection{}, p.fail(err)
		}
		p.additional[choice.ID] = struct{}{}
		return selection, nil
	}
	var selected decision.Selection
	known := false
	unknown := false
	for _, id := range ids {
		d, exists := p.directives[id]
		if !exists {
			p.additional[id] = struct{}{}
			unknown = true
			continue
		}
		if !known {
			selected, known = cloneSelection(d.Selection), true
		} else if !reflect.DeepEqual(selected, d.Selection) {
			return decision.Selection{}, p.fail(ErrCausalConflict)
		}
	}
	if !known {
		selection := decision.Selection{Option: "deliver"}
		if err := decision.ValidateSelection(choice, selection); err != nil {
			// A fixed drop domain is an adapter/environment constraint. It is
			// still additional causal evidence, but the projector must return
			// the only legal choice instead of manufacturing an invalid
			// delivery selection.
			selection, err = p.fallback.Choose(choice)
			if err != nil {
				return decision.Selection{}, p.fail(err)
			}
		}
		return selection, nil
	}
	if selected.Option == "drop" && unknown {
		return decision.Selection{}, p.fail(ErrCausalConflict)
	}
	if err := decision.ValidateSelection(choice, selected); err != nil {
		return decision.Selection{}, p.fail(fmt.Errorf("%w: directive is outside target loss domain: %v", ErrCausalConflict, err))
	}
	for _, id := range ids {
		if _, exists := p.directives[id]; exists {
			p.consumed[id] = struct{}{}
		}
	}
	return selected, nil
}

func (p *CausalProjector) Finish() CausalProjectionReport {
	if p == nil {
		return CausalProjectionReport{Schema: CausalReplaySchema, Fidelity: ProjectionFailed, Additional: []string{}, Unmatched: []CausalDirective{}}
	}
	additional := make([]string, 0, len(p.additional))
	for id := range p.additional {
		additional = append(additional, id)
	}
	slices.Sort(additional)
	unmatched := make([]CausalDirective, 0)
	for id, d := range p.directives {
		if _, ok := p.consumed[id]; !ok {
			unmatched = append(unmatched, d)
		}
	}
	sort.Slice(unmatched, func(i, j int) bool { return unmatched[i].OperationID < unmatched[j].OperationID })
	fidelity := ProjectionExact
	if p.failed != nil {
		fidelity = ProjectionFailed
	} else if len(additional) > 0 || len(unmatched) > 0 {
		fidelity = ProjectionPartial
	}
	report := CausalProjectionReport{Schema: CausalReplaySchema, Fidelity: fidelity, Directives: len(p.directives), Projected: len(p.consumed), Additional: additional, Unmatched: unmatched}
	if err := report.Validate(); err != nil {
		// The projector only constructs bounded in-memory values. Keep a
		// deterministic failed report if a future change violates that
		// invariant rather than returning an invalid artifact.
		return CausalProjectionReport{Schema: CausalReplaySchema, Fidelity: ProjectionFailed, Directives: len(p.directives), Projected: len(p.consumed), Additional: []string{}, Unmatched: []CausalDirective{}}
	}
	return report
}

func (p *CausalProjector) Err() error {
	if p == nil {
		return ErrInvalidCausal
	}
	return p.failed
}

func (p *CausalProjector) fail(err error) error { p.failed = err; return err }
